language: python
python:
  - "3.5"
cache: pip

install:
  - pip install -e .[dev,test]
  - pip install codecov

before_script:
  - python -m flake8 . 
  - python -m pydocstyle .

script:
  - coverage run --source=asyncio_portier --branch -m unittest
  - coverage report -m

after_success:
  - codecov

notifications:
  email:
    on_failure: change
